version: '3'

services:
        web:
          build: public_html/
          container_name: web
          ports: 
            - 80:80
          networks:
            - mynet
          volumes:
            - public_html:/var/www/html
          depends_on:
            - mysql 

        mysql:
           image: mysql
           container_name: mysql
           command: --default-authentication-plugin=mysql_native_password
           environment:
             - MYSQL_ROOT_PASSWORD=123
             - MYSQL_USER=hr_user
             - MYSQL_PASSWORD=123
             - MYSQL_DATABASE=hrdb
           ports:
             - 3306:3306
           networks:
             - mynet
           volumes:
             - mysqldata:/data

networks:
     mynet:
       driver: bridge

volumes:
    public_html:
    mysqldata:
